begin;

alter table public.classes
  add column checkout_mode text not null default 'internal',
  add column external_registration_url text,
  add column instructor_display_text text,
  add column source_schedule_text text,
  add column source_location_text text,
  add column source_category text,
  add column delivery_mode text,
  add column fee_label text,
  add column source_capacity_known boolean not null default true,
  add column source_registration_status text,
  add column source_metadata jsonb not null default '{}'::jsonb,
  add column source_synced_at timestamptz;

alter table public.classes
  add constraint classes_checkout_mode_check
    check (checkout_mode in ('internal', 'external')),
  add constraint classes_external_registration_url_check
    check (external_registration_url is null or external_registration_url ~ '^https://'),
  add constraint classes_external_checkout_url_required
    check (checkout_mode = 'internal' or external_registration_url is not null),
  add constraint classes_external_checkout_status_check
    check (checkout_mode = 'internal' or status not in ('open', 'waitlist')),
  add constraint classes_source_registration_status_check
    check (source_registration_status is null or source_registration_status in ('open', 'waitlist', 'full', 'closed'));

insert into public.programs (code, name, description, audience, status, display_order, legacy_source, legacy_id)
values
  ('ADULT-ART', 'Adult Art Classes', 'Ceramics, drawing, painting, printmaking, and mixed-media classes for adults.', 'Adults ages 18+', 'published', 10, 'art_center_canvas', 'adult-programs'),
  ('YOUTH-ART', 'Youth Art Classes', 'After-school and school-day-off art classes for young artists.', 'Youth ages 6-18', 'published', 20, 'art_center_canvas', 'youth-programs'),
  ('SUMMER-CAMP', 'Summer Art Camp', 'Weeklong summer art camp programs for children and teens.', 'Youth ages 5-16', 'published', 30, 'art_center_canvas', 'summer-camps')
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  audience = excluded.audience,
  status = excluded.status,
  display_order = excluded.display_order,
  legacy_source = excluded.legacy_source,
  legacy_id = excluded.legacy_id,
  updated_at = now();

insert into public.terms (code, name, starts_on, ends_on, status)
values
  ('2026-SUMMER', 'Summer 2026', '2026-06-18', '2026-08-10', 'open'),
  ('2026-FALL', 'Fall 2026', '2026-09-08', '2026-11-15', 'open')
on conflict (code) do update set
  name = excluded.name,
  starts_on = excluded.starts_on,
  ends_on = excluded.ends_on,
  status = excluded.status,
  updated_at = now();

insert into public.facilities (code, name, address_text, status)
values
  ('CER-HANDBUILDING', 'Ceramics Handbuilding', 'Allens Lane Art Center ceramics studio', 'active'),
  ('CER-WHEEL', 'Ceramics Wheel', 'Allens Lane Art Center ceramics studio', 'active'),
  ('STUDIO-1', 'Studio 1', 'Allens Lane Art Center', 'active'),
  ('STUDIO-2', 'Studio 2', 'Allens Lane Art Center', 'active'),
  ('THEATER', 'Theater', 'Allens Lane Art Center', 'active')
on conflict (code) do update set
  name = excluded.name,
  address_text = excluded.address_text,
  status = excluded.status,
  updated_at = now();

with source_rows as (
  select *
  from jsonb_to_recordset($canvas_catalog$
[
  {
    "legacy_id": "564",
    "program_code": "ADULT-ART",
    "term_code": "2026-SUMMER",
    "facility_code": "CER-WHEEL",
    "code": "26U-CER-0002",
    "slug": "ceramics-open-studio-564",
    "title": "Ceramics Open Studio",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 210,
    "member_price": 200,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-06-18 18:30:00",
    "ends_local": "2026-08-06 21:30:00",
    "image_path": "https://alnimages.artcentercanvas.com/library/system/26U-CER-0002_564_1_86278.jpeg",
    "image_alt": "Ceramics Open Studio",
    "external_registration_url": "https://canvas.allenslane.org/classes/564",
    "instructor_display_text": "Ceramics Studio Monitor",
    "source_schedule_text": "Thursday, June 18 - August 6, 2026 (8 sessions) | 6:30 PM – 9:30 PM",
    "source_location_text": "Ceramics Wheel",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "564",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "Ceramics Studio Monitor",
      "schedule": [
        "Thursday, June 18 - August 6, 2026 (8 sessions)",
        "6:30 PM – 9:30 PM"
      ],
      "location": "Ceramics Wheel",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$210.00",
      "member_price": "$200.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/564",
      "image_url": "https://alnimages.artcentercanvas.com/library/system/26U-CER-0002_564_1_86278.jpeg"
    }
  },
  {
    "legacy_id": "575",
    "program_code": "ADULT-ART",
    "term_code": "2026-SUMMER",
    "facility_code": "CER-HANDBUILDING",
    "code": "26U-CER-0013",
    "slug": "monday-evening-pottery-hand-wheel-all-levels-575",
    "title": "Monday Evening Pottery: Hand & Wheel (All Levels)",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 270,
    "member_price": 245,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-06-22 18:30:00",
    "ends_local": "2026-08-10 21:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/575",
    "instructor_display_text": "Malik Nick McDonald",
    "source_schedule_text": "Monday, June 22 - August 10, 2026 (7 sessions) | 6:30 PM – 9:30 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "full",
    "source_metadata": {
      "canvas_id": "575",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "Malik Nick McDonald",
      "schedule": [
        "Monday, June 22 - August 10, 2026 (7 sessions)",
        "6:30 PM – 9:30 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$270.00",
      "member_price": "$245.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Register",
      "is_full": true,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/575",
      "image_url": null
    }
  },
  {
    "legacy_id": "576",
    "program_code": "ADULT-ART",
    "term_code": "2026-SUMMER",
    "facility_code": "STUDIO-1",
    "code": "26U-ADT-0014",
    "slug": "painting-still-life-to-figure-576",
    "title": "Painting: Still Life to Figure",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 265,
    "member_price": 240,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-06-22 18:30:00",
    "ends_local": "2026-08-10 21:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/576",
    "instructor_display_text": "Albert Fung",
    "source_schedule_text": "Monday, June 22 - August 10, 2026 (7 sessions) | 6:30 PM – 9:30 PM",
    "source_location_text": "Studio 1",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "576",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Albert Fung",
      "schedule": [
        "Monday, June 22 - August 10, 2026 (7 sessions)",
        "6:30 PM – 9:30 PM"
      ],
      "location": "Studio 1",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$265.00",
      "member_price": "$240.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/576",
      "image_url": null
    }
  },
  {
    "legacy_id": "572",
    "program_code": "ADULT-ART",
    "term_code": "2026-SUMMER",
    "facility_code": "STUDIO-1",
    "code": "26U-ADT-0010",
    "slug": "introduction-to-the-art-of-bookmaking-572",
    "title": "Introduction to The Art of Bookmaking",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 145,
    "member_price": 130,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-07-16 18:30:00",
    "ends_local": "2026-08-06 21:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/572",
    "instructor_display_text": "Karen Lightner",
    "source_schedule_text": "Thursday, July 16 - August 6, 2026 (4 sessions) | 6:30 PM – 9:30 PM",
    "source_location_text": "Studio 1",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "572",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Karen Lightner",
      "schedule": [
        "Thursday, July 16 - August 6, 2026 (4 sessions)",
        "6:30 PM – 9:30 PM"
      ],
      "location": "Studio 1",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$145.00",
      "member_price": "$130.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/572",
      "image_url": null
    }
  },
  {
    "legacy_id": "517",
    "program_code": "SUMMER-CAMP",
    "term_code": "2026-SUMMER",
    "facility_code": null,
    "code": "26U-SC-0035",
    "slug": "week-8-for-7-8-year-olds-frida-foxes-517",
    "title": "Week 8: (For 7-8 Year Olds: Frida Foxes)",
    "level": "All Levels",
    "age_min": 5,
    "age_max": 16,
    "price": 360,
    "member_price": 345,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-08-03 08:30:00",
    "ends_local": "2026-08-07 15:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/517",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "August 3 - 7, 2026 | 8:30 AM – 3:30 PM",
    "source_location_text": "None Specified",
    "source_category": null,
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "517",
      "category": null,
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "August 3 - 7, 2026",
        "8:30 AM – 3:30 PM"
      ],
      "location": "None Specified",
      "level_age": "All Levels, Ages 5 year-16 year",
      "price": "$360.00",
      "member_price": "$345.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/517",
      "image_url": null
    }
  },
  {
    "legacy_id": "518",
    "program_code": "SUMMER-CAMP",
    "term_code": "2026-SUMMER",
    "facility_code": null,
    "code": "26U-SC-0036",
    "slug": "week-8-for-9-10-year-olds-ringgold-rainbows-518",
    "title": "Week 8: (For 9-10 Year Olds: Ringgold Rainbows)",
    "level": "Children",
    "age_min": 9,
    "age_max": 10,
    "price": 360,
    "member_price": 345,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-08-03 08:30:00",
    "ends_local": "2026-08-07 15:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/518",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "August 3 - 7, 2026 | 8:30 AM – 3:30 PM",
    "source_location_text": "None Specified",
    "source_category": "Mixed Media",
    "delivery_mode": "On-site",
    "source_registration_status": "full",
    "source_metadata": {
      "canvas_id": "518",
      "category": "Mixed Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "August 3 - 7, 2026",
        "8:30 AM – 3:30 PM"
      ],
      "location": "None Specified",
      "level_age": "Children, Ages 9 year-10 year",
      "price": "$360.00",
      "member_price": "$345.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": true,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/518",
      "image_url": null
    }
  },
  {
    "legacy_id": "519",
    "program_code": "SUMMER-CAMP",
    "term_code": "2026-SUMMER",
    "facility_code": null,
    "code": "26U-SC-0038",
    "slug": "week-8-for-11-12-year-olds-leigh-lions-519",
    "title": "Week 8: (For 11-12 Year Olds: Leigh Lions )",
    "level": "Children",
    "age_min": 11,
    "age_max": 12,
    "price": 360,
    "member_price": 345,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-08-03 08:30:00",
    "ends_local": "2026-08-07 15:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/519",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "August 3 - 7, 2026 | 8:30 AM – 3:30 PM",
    "source_location_text": "None Selected",
    "source_category": "Drawing",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "519",
      "category": "Drawing",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "August 3 - 7, 2026",
        "8:30 AM – 3:30 PM"
      ],
      "location": "None Selected",
      "level_age": "Children, Ages 11 year-12 year",
      "price": "$360.00",
      "member_price": "$345.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/519",
      "image_url": null
    }
  },
  {
    "legacy_id": "565",
    "program_code": "ADULT-ART",
    "term_code": "2026-SUMMER",
    "facility_code": "CER-HANDBUILDING",
    "code": "26U-CER-0003",
    "slug": "august-art-date-scratch-sip-sgraffitto-workshop-565",
    "title": "August Art Date - Scratch & Sip: Sgraffitto Workshop",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 40,
    "member_price": 35,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-08-07 18:30:00",
    "ends_local": "2026-08-07 21:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/565",
    "instructor_display_text": "Samantha Moran",
    "source_schedule_text": "Friday, August 7, 2026 | 6:30 PM – 9:00 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "waitlist",
    "source_metadata": {
      "canvas_id": "565",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "Samantha Moran",
      "schedule": [
        "Friday, August 7, 2026",
        "6:30 PM – 9:00 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$40.00",
      "member_price": "$35.00 (members)",
      "fees": [],
      "action": "Join the waitlist",
      "is_full": true,
      "waitlist_only": true,
      "detail_url": "https://canvas.allenslane.org/classes/565",
      "image_url": null
    }
  },
  {
    "legacy_id": "567",
    "program_code": "ADULT-ART",
    "term_code": "2026-SUMMER",
    "facility_code": "STUDIO-1",
    "code": "26U-DTNT-0005",
    "slug": "august-art-date-manifest-melt-candle-making-567",
    "title": "August Art Date - Manifest & Melt: Candle-Making",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 40,
    "member_price": 35,
    "fee": 10,
    "fee_label": "Materials",
    "starts_local": "2026-08-07 18:00:00",
    "ends_local": "2026-08-07 21:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/567",
    "instructor_display_text": "Felicia Crisden",
    "source_schedule_text": "Friday, August 7, 2026 | 6:00 PM – 9:00 PM",
    "source_location_text": "Studio 1",
    "source_category": null,
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "567",
      "category": null,
      "delivery": "On-site",
      "instructor": "Felicia Crisden",
      "schedule": [
        "Friday, August 7, 2026",
        "6:00 PM – 9:00 PM"
      ],
      "location": "Studio 1",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$40.00",
      "member_price": "$35.00 (members)",
      "fees": [
        "+ $10.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/567",
      "image_url": null
    }
  },
  {
    "legacy_id": "595",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-ADT-0017",
    "slug": "tuesday-morning-pottery-handbuilding-with-function-all-levels-595",
    "title": "Tuesday Morning Pottery: Handbuilding with Function (All Levels)",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 300,
    "member_price": 285,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-09-08 10:00:00",
    "ends_local": "2026-11-03 13:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/595",
    "instructor_display_text": "Chloe Theodosiou",
    "source_schedule_text": "Tuesdays, September 8 - November 3, 2026 (9 sessions) | 10:00 AM – 1:00 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "595",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "Chloe Theodosiou",
      "schedule": [
        "Tuesdays, September 8 - November 3, 2026 (9 sessions)",
        "10:00 AM – 1:00 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$300.00",
      "member_price": "$285.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/595",
      "image_url": null
    }
  },
  {
    "legacy_id": "596",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-WHEEL",
    "code": "26F-ADT-0018",
    "slug": "tuesday-evening-pottery-intro-to-wheel-throwing-beginners-596",
    "title": "Tuesday Evening Pottery: Intro to Wheel Throwing (Beginners)",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 300,
    "member_price": 294,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-09-08 18:30:00",
    "ends_local": "2026-11-10 21:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/596",
    "instructor_display_text": "Robin Williams-Turnage",
    "source_schedule_text": "Tuesdays, September 8 - November 10, 2026 (9 sessions) | 6:30 PM – 9:30 PM",
    "source_location_text": "Ceramics Wheel",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "waitlist",
    "source_metadata": {
      "canvas_id": "596",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "Robin Williams-Turnage",
      "schedule": [
        "Tuesdays, September 8 - November 10, 2026 (9 sessions)",
        "6:30 PM – 9:30 PM"
      ],
      "location": "Ceramics Wheel",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$300.00",
      "member_price": "$294.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Join the waitlist",
      "is_full": true,
      "waitlist_only": true,
      "detail_url": "https://canvas.allenslane.org/classes/596",
      "image_url": null
    }
  },
  {
    "legacy_id": "602",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-1",
    "code": "26F-ADT-0024",
    "slug": "figure-drawing-open-studio-602",
    "title": "Figure Drawing Open Studio",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 135,
    "member_price": 128,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-09-08 18:30:00",
    "ends_local": "2026-11-10 21:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/602",
    "instructor_display_text": "Peter Samuel",
    "source_schedule_text": "Tuesdays, September 8 - November 10, 2026 (9 sessions) | 6:30 PM – 9:30 PM",
    "source_location_text": "Studio 1",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "602",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Peter Samuel",
      "schedule": [
        "Tuesdays, September 8 - November 10, 2026 (9 sessions)",
        "6:30 PM – 9:30 PM"
      ],
      "location": "Studio 1",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$135.00",
      "member_price": "$128.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/602",
      "image_url": null
    }
  },
  {
    "legacy_id": "613",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "THEATER",
    "code": "26F-5-0037",
    "slug": "after-school-studio-youth-theater-books-to-plays-613",
    "title": "After School Studio: Youth Theater Books-to-Plays",
    "level": "Children",
    "age_min": 6,
    "age_max": 9,
    "price": 180,
    "member_price": 171,
    "fee": 10,
    "fee_label": "Materials",
    "starts_local": "2026-09-08 16:00:00",
    "ends_local": "2026-11-03 17:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/613",
    "instructor_display_text": "Josh Gold",
    "source_schedule_text": "Tuesdays, September 8 - November 3, 2026 (8 sessions) | 4:00 PM – 5:30 PM",
    "source_location_text": "Theater",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "613",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Josh Gold",
      "schedule": [
        "Tuesdays, September 8 - November 3, 2026 (8 sessions)",
        "4:00 PM – 5:30 PM"
      ],
      "location": "Theater",
      "level_age": "Children, Ages 6 year-9 year",
      "price": "$180.00",
      "member_price": "$171.00 (members)",
      "fees": [
        "+ $10.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/613",
      "image_url": null
    }
  },
  {
    "legacy_id": "614",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-5-0038",
    "slug": "after-school-studio-clay-creations-614",
    "title": "After School Studio: Clay Creations",
    "level": "Children",
    "age_min": 9,
    "age_max": 13,
    "price": 180,
    "member_price": 171,
    "fee": 10,
    "fee_label": "Materials",
    "starts_local": "2026-09-08 16:00:00",
    "ends_local": "2026-10-27 17:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/614",
    "instructor_display_text": "Zipora Schulz",
    "source_schedule_text": "Tuesdays, September 8 - October 27, 2026 (8 sessions) | 4:00 PM – 5:30 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "614",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Zipora Schulz",
      "schedule": [
        "Tuesdays, September 8 - October 27, 2026 (8 sessions)",
        "4:00 PM – 5:30 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "Children, Ages 9 year-13 year",
      "price": "$180.00",
      "member_price": "$171.00 (members)",
      "fees": [
        "+ $10.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/614",
      "image_url": null
    }
  },
  {
    "legacy_id": "580",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-2",
    "code": "26F-ADT-0001",
    "slug": "acrylic-painting-painting-with-spirit-580",
    "title": "Acrylic Painting: Painting with Spirit",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 195,
    "member_price": 185,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-09-09 18:30:00",
    "ends_local": "2026-11-04 20:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/580",
    "instructor_display_text": "Inga Kimberly Brown",
    "source_schedule_text": "Wednesdays, September 9 - November 4, 2026 (9 sessions) | 6:30 PM – 8:30 PM",
    "source_location_text": "Studio 2",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "580",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Inga Kimberly Brown",
      "schedule": [
        "Wednesdays, September 9 - November 4, 2026 (9 sessions)",
        "6:30 PM – 8:30 PM"
      ],
      "location": "Studio 2",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$195.00",
      "member_price": "$185.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/580",
      "image_url": null
    }
  },
  {
    "legacy_id": "585",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-2",
    "code": "26F-ADT-0006",
    "slug": "mixed-media-painting-getting-started-585",
    "title": "Mixed Media Painting: Getting Started",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 165,
    "member_price": 157,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-09-09 10:00:00",
    "ends_local": "2026-10-07 13:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/585",
    "instructor_display_text": "Ife Nii Owoo",
    "source_schedule_text": "Wednesdays, September 9 - October 7, 2026 (5 sessions) | 10:00 AM – 1:00 PM",
    "source_location_text": "Studio 2",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "585",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Ife Nii Owoo",
      "schedule": [
        "Wednesdays, September 9 - October 7, 2026 (5 sessions)",
        "10:00 AM – 1:00 PM"
      ],
      "location": "Studio 2",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$165.00",
      "member_price": "$157.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/585",
      "image_url": null
    }
  },
  {
    "legacy_id": "599",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-ADT-0021",
    "slug": "wednesday-afternoon-handbuilding-functional-to-sculptural-all-levels-599",
    "title": "Wednesday Afternoon Handbuilding: Functional to Sculptural (All Levels)",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 300,
    "member_price": 285,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-09-09 13:00:00",
    "ends_local": "2026-11-04 16:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/599",
    "instructor_display_text": "Samantha Moran",
    "source_schedule_text": "Wednesdays, September 9 - November 4, 2026 (9 sessions) | 1:00 PM – 4:00 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "599",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "Samantha Moran",
      "schedule": [
        "Wednesdays, September 9 - November 4, 2026 (9 sessions)",
        "1:00 PM – 4:00 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$300.00",
      "member_price": "$285.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/599",
      "image_url": null
    }
  },
  {
    "legacy_id": "600",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-ADT-0022",
    "slug": "wednesday-evening-pottery-hand-wheel-all-levels-600",
    "title": "Wednesday Evening Pottery: Hand & Wheel (All Levels)",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 300,
    "member_price": 285,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-09-09 18:30:00",
    "ends_local": "2026-11-11 21:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/600",
    "instructor_display_text": "Samantha Moran",
    "source_schedule_text": "Wednesdays, September 9 - November 11, 2026 (9 sessions) | 6:30 PM – 9:30 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "600",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Samantha Moran",
      "schedule": [
        "Wednesdays, September 9 - November 11, 2026 (9 sessions)",
        "6:30 PM – 9:30 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$300.00",
      "member_price": "$285.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/600",
      "image_url": null
    }
  },
  {
    "legacy_id": "615",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-2",
    "code": "26F-5-0039",
    "slug": "after-school-studio-fantastic-fibers-615",
    "title": "After School Studio: Fantastic Fibers",
    "level": "Children",
    "age_min": 6,
    "age_max": 9,
    "price": 180,
    "member_price": 171,
    "fee": 10,
    "fee_label": "Materials",
    "starts_local": "2026-09-09 16:00:00",
    "ends_local": "2026-11-04 17:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/615",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Wednesdays, September 9 - November 4, 2026 (8 sessions) | 4:00 PM – 5:30 PM",
    "source_location_text": "Studio 2",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "615",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Wednesdays, September 9 - November 4, 2026 (8 sessions)",
        "4:00 PM – 5:30 PM"
      ],
      "location": "Studio 2",
      "level_age": "Children, Ages 6 year-9 year",
      "price": "$180.00",
      "member_price": "$171.00 (members)",
      "fees": [
        "+ $10.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/615",
      "image_url": null
    }
  },
  {
    "legacy_id": "616",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-1",
    "code": "26F-5-0040",
    "slug": "after-school-studio-print-party-616",
    "title": "After School Studio: Print Party",
    "level": "Children",
    "age_min": 9,
    "age_max": 13,
    "price": 180,
    "member_price": 171,
    "fee": 10,
    "fee_label": "Materials",
    "starts_local": "2026-09-09 16:00:00",
    "ends_local": "2026-11-04 17:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/616",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Wednesdays, September 9 - November 4, 2026 (8 sessions) | 4:00 PM – 5:30 PM",
    "source_location_text": "Studio 1",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "616",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Wednesdays, September 9 - November 4, 2026 (8 sessions)",
        "4:00 PM – 5:30 PM"
      ],
      "location": "Studio 1",
      "level_age": "Children, Ages 9 year-13 year",
      "price": "$180.00",
      "member_price": "$171.00 (members)",
      "fees": [
        "+ $10.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/616",
      "image_url": null
    }
  },
  {
    "legacy_id": "627",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-WHEEL",
    "code": "26F-5-0054",
    "slug": "teens-pottery-spin-build-627",
    "title": "Teens Pottery: Spin & Build",
    "level": "Children",
    "age_min": 13,
    "age_max": 18,
    "price": 155,
    "member_price": 147,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-09-09 16:15:00",
    "ends_local": "2026-10-28 17:45:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/627",
    "instructor_display_text": "Robin Williams-Turnage",
    "source_schedule_text": "Wednesdays, September 9 - October 28, 2026 (8 sessions) | 4:15 PM – 5:45 PM",
    "source_location_text": "Ceramics Wheel",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "627",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Robin Williams-Turnage",
      "schedule": [
        "Wednesdays, September 9 - October 28, 2026 (8 sessions)",
        "4:15 PM – 5:45 PM"
      ],
      "location": "Ceramics Wheel",
      "level_age": "Children, Ages 13 year-18 year",
      "price": "$155.00",
      "member_price": "$147.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/627",
      "image_url": null
    }
  },
  {
    "legacy_id": "583",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-1",
    "code": "26F-ADT-0004",
    "slug": "first-lines-the-joy-of-drawing-583",
    "title": "First Lines: The Joy of Drawing",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 265,
    "member_price": 252,
    "fee": 15,
    "fee_label": "Model Fee",
    "starts_local": "2026-09-10 18:30:00",
    "ends_local": "2026-10-29 21:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/583",
    "instructor_display_text": "Emilio  Maldonado",
    "source_schedule_text": "Thursdays, September 10 - October 29, 2026 (8 sessions) | 6:30 PM – 9:30 PM",
    "source_location_text": "Studio 1",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "583",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Emilio  Maldonado",
      "schedule": [
        "Thursdays, September 10 - October 29, 2026 (8 sessions)",
        "6:30 PM – 9:30 PM"
      ],
      "location": "Studio 1",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$265.00",
      "member_price": "$252.00 (members)",
      "fees": [
        "+ $15.00 (Model Fee)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/583",
      "image_url": null
    }
  },
  {
    "legacy_id": "594",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-WHEEL",
    "code": "26F-ADT-0016",
    "slug": "thursday-morning-wheel-throwing-all-levels-594",
    "title": "Thursday Morning Wheel Throwing (All Levels)",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 330,
    "member_price": 314,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-09-10 10:00:00",
    "ends_local": "2026-11-12 13:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/594",
    "instructor_display_text": "Nathan Willever",
    "source_schedule_text": "Thursdays, September 10 - November 12, 2026 (10 sessions) | 10:00 AM – 1:00 PM",
    "source_location_text": "Ceramics Wheel",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "594",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "Nathan Willever",
      "schedule": [
        "Thursdays, September 10 - November 12, 2026 (10 sessions)",
        "10:00 AM – 1:00 PM"
      ],
      "location": "Ceramics Wheel",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$330.00",
      "member_price": "$314.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/594",
      "image_url": null
    }
  },
  {
    "legacy_id": "603",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-1",
    "code": "26F-ADT-0025",
    "slug": "figure-drawing-open-studio-long-pose-603",
    "title": "Figure Drawing Open Studio: Long Pose",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 150,
    "member_price": 143,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-09-10 13:00:00",
    "ends_local": "2026-11-12 16:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/603",
    "instructor_display_text": "Peter Samuel",
    "source_schedule_text": "Thursdays, September 10 - November 12, 2026 (10 sessions) | 1:00 PM – 4:00 PM",
    "source_location_text": "Studio 1",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "603",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Peter Samuel",
      "schedule": [
        "Thursdays, September 10 - November 12, 2026 (10 sessions)",
        "1:00 PM – 4:00 PM"
      ],
      "location": "Studio 1",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$150.00",
      "member_price": "$143.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/603",
      "image_url": null
    }
  },
  {
    "legacy_id": "617",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-2",
    "code": "26F-5-0041",
    "slug": "after-school-studio-mixed-media-fun-617",
    "title": "After School Studio: Mixed Media Fun",
    "level": "Children",
    "age_min": 6,
    "age_max": 9,
    "price": 191,
    "member_price": 185,
    "fee": 10,
    "fee_label": "Materials",
    "starts_local": "2026-09-10 16:00:00",
    "ends_local": "2026-11-12 17:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/617",
    "instructor_display_text": "Lexi Arrietta",
    "source_schedule_text": "Thursdays, September 10 - November 12, 2026 (10 sessions) | 4:00 PM – 5:30 PM",
    "source_location_text": "Studio 2",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "617",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Lexi Arrietta",
      "schedule": [
        "Thursdays, September 10 - November 12, 2026 (10 sessions)",
        "4:00 PM – 5:30 PM"
      ],
      "location": "Studio 2",
      "level_age": "Children, Ages 6 year-9 year",
      "price": "$191.00",
      "member_price": "$185.00 (members)",
      "fees": [
        "+ $10.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/617",
      "image_url": null
    }
  },
  {
    "legacy_id": "618",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-1",
    "code": "26F-5-0042",
    "slug": "after-school-studio-comic-creations-618",
    "title": "After School Studio: Comic Creations",
    "level": "Children",
    "age_min": 9,
    "age_max": 13,
    "price": 195,
    "member_price": 185,
    "fee": 10,
    "fee_label": "Materials",
    "starts_local": "2026-09-10 16:00:00",
    "ends_local": "2026-11-12 17:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/618",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Thursdays, September 10 - November 12, 2026 (10 sessions) | 4:00 PM – 5:30 PM",
    "source_location_text": "Studio 1",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "618",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Thursdays, September 10 - November 12, 2026 (10 sessions)",
        "4:00 PM – 5:30 PM"
      ],
      "location": "Studio 1",
      "level_age": "Children, Ages 9 year-13 year",
      "price": "$195.00",
      "member_price": "$185.00 (members)",
      "fees": [
        "+ $10.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/618",
      "image_url": null
    }
  },
  {
    "legacy_id": "619",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-5-0043",
    "slug": "after-school-studio-clay-play-619",
    "title": "After School Studio: Clay Play",
    "level": "Children",
    "age_min": 6,
    "age_max": 9,
    "price": 195,
    "member_price": 185,
    "fee": 10,
    "fee_label": "Materials",
    "starts_local": "2026-09-11 16:00:00",
    "ends_local": "2026-11-13 17:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/619",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Fridays, September 11 - November 13, 2026 (10 sessions) | 4:00 PM – 5:30 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "619",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Fridays, September 11 - November 13, 2026 (10 sessions)",
        "4:00 PM – 5:30 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "Children, Ages 6 year-9 year",
      "price": "$195.00",
      "member_price": "$185.00 (members)",
      "fees": [
        "+ $10.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/619",
      "image_url": null
    }
  },
  {
    "legacy_id": "626",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-1",
    "code": "26F-5-0044",
    "slug": "after-school-studio-craft-lab-626",
    "title": "After School Studio: Craft Lab",
    "level": "Children",
    "age_min": 9,
    "age_max": 13,
    "price": 195,
    "member_price": 185,
    "fee": 10,
    "fee_label": "Materials",
    "starts_local": "2026-09-11 16:00:00",
    "ends_local": "2026-11-13 17:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/626",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Fridays, September 11 - November 13, 2026 (10 sessions) | 4:00 PM – 5:30 PM",
    "source_location_text": "Studio 1",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "626",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Fridays, September 11 - November 13, 2026 (10 sessions)",
        "4:00 PM – 5:30 PM"
      ],
      "location": "Studio 1",
      "level_age": "Children, Ages 9 year-13 year",
      "price": "$195.00",
      "member_price": "$185.00 (members)",
      "fees": [
        "+ $10.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/626",
      "image_url": null
    }
  },
  {
    "legacy_id": "591",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-ADT-0013",
    "slug": "saturday-morning-intro-to-pottery-beginners-591",
    "title": "Saturday Morning: Intro to Pottery (Beginners)",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 330,
    "member_price": 314,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-09-12 10:00:00",
    "ends_local": "2026-11-14 13:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/591",
    "instructor_display_text": "Chloe Theodosiou",
    "source_schedule_text": "Saturdays, September 12 - November 14, 2026 (10 sessions) | 10:00 AM – 1:00 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "591",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Chloe Theodosiou",
      "schedule": [
        "Saturdays, September 12 - November 14, 2026 (10 sessions)",
        "10:00 AM – 1:00 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$330.00",
      "member_price": "$314.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/591",
      "image_url": null
    }
  },
  {
    "legacy_id": "601",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-CER-0023",
    "slug": "ceramics-open-studio-601",
    "title": "Ceramics Open Studio",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 200,
    "member_price": 190,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-09-13 13:00:00",
    "ends_local": "2026-11-08 16:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/601",
    "instructor_display_text": "Ceramics Studio Monitor",
    "source_schedule_text": "Tuesdays, September 13 - November 8, 2026 (9 sessions) | 1:00 PM – 4:00 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "601",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "Ceramics Studio Monitor",
      "schedule": [
        "Tuesdays, September 13 - November 8, 2026 (9 sessions)",
        "1:00 PM – 4:00 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$200.00",
      "member_price": "$190.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/601",
      "image_url": null
    }
  },
  {
    "legacy_id": "604",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-ADT-0026",
    "slug": "glazing-workshop-breaking-bad-habits-604",
    "title": "Glazing Workshop: Breaking Bad Habits",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 80,
    "member_price": 76,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-09-13 10:00:00",
    "ends_local": "2026-09-13 13:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/604",
    "instructor_display_text": "Chloe Theodosiou",
    "source_schedule_text": "Sunday, September 13, 2026 | 10:00 AM – 1:00 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "604",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "Chloe Theodosiou",
      "schedule": [
        "Sunday, September 13, 2026",
        "10:00 AM – 1:00 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$80.00",
      "member_price": "$76.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/604",
      "image_url": null
    }
  },
  {
    "legacy_id": "581",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-1",
    "code": "26F-ADT-0002",
    "slug": "acrylic-painting-vivid-visions-581",
    "title": "Acrylic Painting: Vivid Visions",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 300,
    "member_price": 285,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-09-14 18:30:00",
    "ends_local": "2026-11-09 21:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/581",
    "instructor_display_text": "Dara Haskins",
    "source_schedule_text": "Mondays, September 14 - November 9, 2026 (8 sessions) | 6:30 PM – 9:30 PM",
    "source_location_text": "Studio 1",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "581",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Dara Haskins",
      "schedule": [
        "Mondays, September 14 - November 9, 2026 (8 sessions)",
        "6:30 PM – 9:30 PM"
      ],
      "location": "Studio 1",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$300.00",
      "member_price": "$285.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/581",
      "image_url": null
    }
  },
  {
    "legacy_id": "584",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-2",
    "code": "26F-ADT-0005",
    "slug": "linoleum-printmaking-block-and-roll-584",
    "title": "Linoleum Printmaking: Block and Roll!",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 165,
    "member_price": 157,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-09-14 18:30:00",
    "ends_local": "2026-10-05 20:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/584",
    "instructor_display_text": "Romy Burkus",
    "source_schedule_text": "Mondays, September 14 - October 5, 2026 (4 sessions) | 6:30 PM – 8:30 PM",
    "source_location_text": "Studio 2",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "584",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Romy Burkus",
      "schedule": [
        "Mondays, September 14 - October 5, 2026 (4 sessions)",
        "6:30 PM – 8:30 PM"
      ],
      "location": "Studio 2",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$165.00",
      "member_price": "$157.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/584",
      "image_url": null
    }
  },
  {
    "legacy_id": "587",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": null,
    "code": "26F-ADT-0008",
    "slug": "monday-morning-pottery-hand-wheel-all-levels-587",
    "title": "Monday Morning Pottery: Hand & Wheel (All Levels)",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 300,
    "member_price": 285,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-09-14 10:00:00",
    "ends_local": "2026-11-09 13:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/587",
    "instructor_display_text": "Chloe Theodosiou",
    "source_schedule_text": "Mondays, September 14 - November 9, 2026 (8 sessions) | 10:00 AM – 1:00 PM",
    "source_location_text": "None Specified",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "587",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "Chloe Theodosiou",
      "schedule": [
        "Mondays, September 14 - November 9, 2026 (8 sessions)",
        "10:00 AM – 1:00 PM"
      ],
      "location": "None Specified",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$300.00",
      "member_price": "$285.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/587",
      "image_url": null
    }
  },
  {
    "legacy_id": "588",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": null,
    "code": "26F-ADT-0009",
    "slug": "monday-evening-pottery-hand-wheel-all-levels-588",
    "title": "Monday Evening Pottery: Hand & Wheel (All Levels)",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 300,
    "member_price": 285,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-09-14 18:30:00",
    "ends_local": "2026-11-09 21:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/588",
    "instructor_display_text": "Malik Nick McDonald",
    "source_schedule_text": "Mondays, September 14 - November 9, 2026 (8 sessions) | 6:30 PM – 9:30 PM",
    "source_location_text": "None Specified",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "waitlist",
    "source_metadata": {
      "canvas_id": "588",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "Malik Nick McDonald",
      "schedule": [
        "Mondays, September 14 - November 9, 2026 (8 sessions)",
        "6:30 PM – 9:30 PM"
      ],
      "location": "None Specified",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$300.00",
      "member_price": "$285.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Join the waitlist",
      "is_full": true,
      "waitlist_only": true,
      "detail_url": "https://canvas.allenslane.org/classes/588",
      "image_url": null
    }
  },
  {
    "legacy_id": "611",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-2",
    "code": "26F-5-0035",
    "slug": "after-school-studio-make-your-mark-611",
    "title": "After School Studio: Make Your Mark",
    "level": "Children",
    "age_min": 6,
    "age_max": 9,
    "price": 180,
    "member_price": 171,
    "fee": 10,
    "fee_label": "Materials",
    "starts_local": "2026-09-14 16:00:00",
    "ends_local": "2026-11-09 17:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/611",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Mondays, September 14 - November 9, 2026 (9 sessions) | 4:00 PM – 5:30 PM",
    "source_location_text": "Studio 2",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "611",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Mondays, September 14 - November 9, 2026 (9 sessions)",
        "4:00 PM – 5:30 PM"
      ],
      "location": "Studio 2",
      "level_age": "Children, Ages 6 year-9 year",
      "price": "$180.00",
      "member_price": "$171.00 (members)",
      "fees": [
        "+ $10.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/611",
      "image_url": null
    }
  },
  {
    "legacy_id": "612",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "THEATER",
    "code": "26F-5-0036",
    "slug": "after-school-studio-theater-improv-612",
    "title": "After School Studio: Theater Improv",
    "level": "Children",
    "age_min": 9,
    "age_max": 13,
    "price": 180,
    "member_price": 171,
    "fee": 10,
    "fee_label": "Materials",
    "starts_local": "2026-09-14 16:00:00",
    "ends_local": "2026-11-09 17:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/612",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Mondays, September 14 - November 9, 2026 (8 sessions) | 4:00 PM – 5:30 PM",
    "source_location_text": "Theater",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "612",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Mondays, September 14 - November 9, 2026 (8 sessions)",
        "4:00 PM – 5:30 PM"
      ],
      "location": "Theater",
      "level_age": "Children, Ages 9 year-13 year",
      "price": "$180.00",
      "member_price": "$171.00 (members)",
      "fees": [
        "+ $10.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/612",
      "image_url": null
    }
  },
  {
    "legacy_id": "597",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-1",
    "code": "26F-ADT-0020",
    "slug": "watercolor-flow-a-guided-open-studio-597",
    "title": "Watercolor & Flow: A Guided Open Studio",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 195,
    "member_price": 185,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-09-15 19:00:00",
    "ends_local": "2026-11-10 21:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/597",
    "instructor_display_text": "Albert Fung",
    "source_schedule_text": "Tuesdays, September 15 - November 10, 2026 (9 sessions) | 7:00 PM – 9:00 PM",
    "source_location_text": "Studio 1",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "597",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Albert Fung",
      "schedule": [
        "Tuesdays, September 15 - November 10, 2026 (9 sessions)",
        "7:00 PM – 9:00 PM"
      ],
      "location": "Studio 1",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$195.00",
      "member_price": "$185.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/597",
      "image_url": null
    }
  },
  {
    "legacy_id": "622",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-5-0049",
    "slug": "day-off-camp-ceramics-workshop-for-ages-9-12-622",
    "title": "Day off Camp: Ceramics Workshop for ages 9-12",
    "level": "Children",
    "age_min": 9,
    "age_max": 12,
    "price": 80,
    "member_price": 76,
    "fee": 10,
    "fee_label": "None",
    "starts_local": "2026-09-18 09:00:00",
    "ends_local": "2026-09-18 15:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/622",
    "instructor_display_text": "Chloe Theodosiou",
    "source_schedule_text": "Friday, September 18, 2026 | 9:00 AM – 3:30 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "622",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Chloe Theodosiou",
      "schedule": [
        "Friday, September 18, 2026",
        "9:00 AM – 3:30 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "Children, Ages 9 year-12 year",
      "price": "$80.00",
      "member_price": "$76.00 (members)",
      "fees": [
        "+ $10.00 (None)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/622",
      "image_url": null
    }
  },
  {
    "legacy_id": "623",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "THEATER",
    "code": "26F-5-0050",
    "slug": "day-off-camp-theater-workshop-for-ages-6-8-623",
    "title": "Day Off Camp: Theater Workshop for ages 6-8",
    "level": "Children",
    "age_min": 6,
    "age_max": 8,
    "price": 80,
    "member_price": 76,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-09-18 09:00:00",
    "ends_local": "2026-09-18 15:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/623",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Friday, September 18, 2026 | 9:00 AM – 3:30 PM",
    "source_location_text": "Theater",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "623",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Friday, September 18, 2026",
        "9:00 AM – 3:30 PM"
      ],
      "location": "Theater",
      "level_age": "Children, Ages 6 year-8 year",
      "price": "$80.00",
      "member_price": "$76.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/623",
      "image_url": null
    }
  },
  {
    "legacy_id": "628",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-ADT-0027",
    "slug": "make-it-friday-workshop-slab-vases-september-628",
    "title": "Make-It Friday Workshop: Slab Vases September",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 35,
    "member_price": 33,
    "fee": 10,
    "fee_label": "Gas Kiln Fee",
    "starts_local": "2026-09-18 18:00:00",
    "ends_local": "2026-09-18 21:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/628",
    "instructor_display_text": "Chloe Theodosiou",
    "source_schedule_text": "Friday, September 18, 2026 | 6:00 PM – 9:00 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "628",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Chloe Theodosiou",
      "schedule": [
        "Friday, September 18, 2026",
        "6:00 PM – 9:00 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$35.00",
      "member_price": "$33.00 (members)",
      "fees": [
        "+ $10.00 (Gas Kiln Fee)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/628",
      "image_url": null
    }
  },
  {
    "legacy_id": "592",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": null,
    "code": "26F-ADT-0014",
    "slug": "stained-glass-basics-off-site-592",
    "title": "Stained Glass Basics (off-site)",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 250,
    "member_price": 238,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-09-22 18:30:00",
    "ends_local": "2026-10-06 21:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/592",
    "instructor_display_text": "Greg Stefan",
    "source_schedule_text": "Tuesdays, September 22 - October 6, 2026 (3 sessions) | 6:30 PM – 9:00 PM",
    "source_location_text": "None Selected",
    "source_category": "Mixed Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "592",
      "category": "Mixed Media",
      "delivery": "On-site",
      "instructor": "Greg Stefan",
      "schedule": [
        "Tuesdays, September 22 - October 6, 2026 (3 sessions)",
        "6:30 PM – 9:00 PM"
      ],
      "location": "None Selected",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$250.00",
      "member_price": "$238.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/592",
      "image_url": null
    }
  },
  {
    "legacy_id": "624",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-5-0051",
    "slug": "day-off-camp-ceramics-workshop-for-ages-6-8-624",
    "title": "Day off Camp: Ceramics Workshop for ages 6-8",
    "level": "Children",
    "age_min": 6,
    "age_max": 8,
    "price": 80,
    "member_price": 76,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-10-09 09:00:00",
    "ends_local": "2026-10-09 15:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/624",
    "instructor_display_text": "Chloe Theodosiou",
    "source_schedule_text": "Friday, October 9, 2026 | 9:00 AM – 3:30 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "624",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Chloe Theodosiou",
      "schedule": [
        "Friday, October 9, 2026",
        "9:00 AM – 3:30 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "Children, Ages 6 year-8 year",
      "price": "$80.00",
      "member_price": "$76.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/624",
      "image_url": null
    }
  },
  {
    "legacy_id": "625",
    "program_code": "YOUTH-ART",
    "term_code": "2026-FALL",
    "facility_code": "THEATER",
    "code": "26F-5-0052",
    "slug": "day-off-camp-theater-workshop-for-ages-9-12-625",
    "title": "Day Off Camp: Theater Workshop for ages 9-12",
    "level": "Children",
    "age_min": 9,
    "age_max": 12,
    "price": 80,
    "member_price": 76,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-10-09 09:00:00",
    "ends_local": "2026-10-09 15:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/625",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Friday, October 9, 2026 | 9:00 AM – 3:30 PM",
    "source_location_text": "Theater",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "625",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Friday, October 9, 2026",
        "9:00 AM – 3:30 PM"
      ],
      "location": "Theater",
      "level_age": "Children, Ages 9 year-12 year",
      "price": "$80.00",
      "member_price": "$76.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/625",
      "image_url": null
    }
  },
  {
    "legacy_id": "593",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-ADT-0015",
    "slug": "sunday-morning-nerikomi-593",
    "title": "Sunday Morning: Nerikomi",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 165,
    "member_price": 157,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-10-11 10:00:00",
    "ends_local": "2026-11-15 13:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/593",
    "instructor_display_text": "Mackenzie Pikaart",
    "source_schedule_text": "Sundays, October 11 - November 15, 2026 (6 sessions) | 10:00 AM – 1:00 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "593",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "Mackenzie Pikaart",
      "schedule": [
        "Sundays, October 11 - November 15, 2026 (6 sessions)",
        "10:00 AM – 1:00 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$165.00",
      "member_price": "$157.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/593",
      "image_url": null
    }
  },
  {
    "legacy_id": "590",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-ADT-0012",
    "slug": "raku-firing-october-monday-590",
    "title": "Raku Firing October: MONDAY!",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 100,
    "member_price": 95,
    "fee": 35,
    "fee_label": "Materials",
    "starts_local": "2026-10-12 10:00:00",
    "ends_local": "2026-10-12 16:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/590",
    "instructor_display_text": "Chloe Theodosiou",
    "source_schedule_text": "Monday, October 12, 2026 | 10:00 AM – 4:00 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "590",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "Chloe Theodosiou",
      "schedule": [
        "Monday, October 12, 2026",
        "10:00 AM – 4:00 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$100.00",
      "member_price": "$95.00 (members)",
      "fees": [
        "+ $35.00 (Materials)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/590",
      "image_url": null
    }
  },
  {
    "legacy_id": "586",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-2",
    "code": "26F-ADT-0007",
    "slug": "mixed-media-painting-personal-projects-586",
    "title": "Mixed Media Painting: Personal Projects",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 135,
    "member_price": 128,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-10-14 10:00:00",
    "ends_local": "2026-11-04 13:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/586",
    "instructor_display_text": "Ife Nii Owoo",
    "source_schedule_text": "Wednesdays, October 14 - November 4, 2026 (4 sessions) | 10:00 AM – 1:00 PM",
    "source_location_text": "Studio 2",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "586",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Ife Nii Owoo",
      "schedule": [
        "Wednesdays, October 14 - November 4, 2026 (4 sessions)",
        "10:00 AM – 1:00 PM"
      ],
      "location": "Studio 2",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$135.00",
      "member_price": "$128.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/586",
      "image_url": null
    }
  },
  {
    "legacy_id": "598",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-2",
    "code": "26F-ADT-0019",
    "slug": "watercolor-basics-598",
    "title": "Watercolor Basics",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 195,
    "member_price": 185,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-10-14 13:00:00",
    "ends_local": "2026-11-11 16:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/598",
    "instructor_display_text": "Albert Fung",
    "source_schedule_text": "Mondays, October 14 - November 11, 2026 (5 sessions) | 1:00 PM – 4:00 PM",
    "source_location_text": "Studio 2",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "598",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Albert Fung",
      "schedule": [
        "Mondays, October 14 - November 11, 2026 (5 sessions)",
        "1:00 PM – 4:00 PM"
      ],
      "location": "Studio 2",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$195.00",
      "member_price": "$185.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/598",
      "image_url": null
    }
  },
  {
    "legacy_id": "582",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-2",
    "code": "26F-ADT-0003",
    "slug": "crochet-fun-with-the-basics-582",
    "title": "Crochet: Fun with the basics",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 120,
    "member_price": 114,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-10-15 18:30:00",
    "ends_local": "2026-11-12 20:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/582",
    "instructor_display_text": "Tee James",
    "source_schedule_text": "Thursdays, October 15 - November 12, 2026 (5 sessions) | 6:30 PM – 8:30 PM",
    "source_location_text": "Studio 2",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "582",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Tee James",
      "schedule": [
        "Thursdays, October 15 - November 12, 2026 (5 sessions)",
        "6:30 PM – 8:30 PM"
      ],
      "location": "Studio 2",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$120.00",
      "member_price": "$114.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/582",
      "image_url": null
    }
  },
  {
    "legacy_id": "606",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-2",
    "code": "26F-ADT-0029",
    "slug": "make-it-friday-workshop-upcycled-earrings-workshop-2-pairs-606",
    "title": "Make-It Friday Workshop: Upcycled Earrings Workshop (2-pairs)",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 35,
    "member_price": 33,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-10-16 18:00:00",
    "ends_local": "2026-10-16 20:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/606",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Friday, October 16, 2026 | 6:00 PM – 8:30 PM",
    "source_location_text": "Studio 2",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "606",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Friday, October 16, 2026",
        "6:00 PM – 8:30 PM"
      ],
      "location": "Studio 2",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$35.00",
      "member_price": "$33.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/606",
      "image_url": null
    }
  },
  {
    "legacy_id": "607",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-ADT-0030",
    "slug": "make-it-friday-workshop-mug-nificent-mugs-october-607",
    "title": "Make-It Friday Workshop: Mug-nificent Mugs October",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 35,
    "member_price": 33,
    "fee": 10,
    "fee_label": "Gas Kiln Fee",
    "starts_local": "2026-10-16 18:00:00",
    "ends_local": "2026-10-16 20:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/607",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Friday, October 16, 2026 | 6:00 PM – 8:00 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "607",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Friday, October 16, 2026",
        "6:00 PM – 8:00 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$35.00",
      "member_price": "$33.00 (members)",
      "fees": [
        "+ $10.00 (Gas Kiln Fee)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/607",
      "image_url": null
    }
  },
  {
    "legacy_id": "608",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-1",
    "code": "26F-ADT-0032",
    "slug": "make-it-friday-workshop-spooky-screenprinting-608",
    "title": "Make-It Friday Workshop: Spooky Screenprinting!",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 35,
    "member_price": 33,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-10-16 18:30:00",
    "ends_local": "2026-10-16 21:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/608",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Friday, October 16, 2026 | 6:30 PM – 9:30 PM",
    "source_location_text": "Studio 1",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "608",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Friday, October 16, 2026",
        "6:30 PM – 9:30 PM"
      ],
      "location": "Studio 1",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$35.00",
      "member_price": "$33.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/608",
      "image_url": null
    }
  },
  {
    "legacy_id": "589",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-2",
    "code": "26F-ADT-0010",
    "slug": "oil-paint-monotypes-painterly-prints-589",
    "title": "Oil Paint Monotypes: Painterly Prints",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 135,
    "member_price": 128,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-10-19 18:30:00",
    "ends_local": "2026-11-09 20:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/589",
    "instructor_display_text": "Romy Burkus",
    "source_schedule_text": "Mondays, October 19 - November 9, 2026 (4 sessions) | 6:30 PM – 8:30 PM",
    "source_location_text": "Studio 2",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "589",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Romy Burkus",
      "schedule": [
        "Mondays, October 19 - November 9, 2026 (4 sessions)",
        "6:30 PM – 8:30 PM"
      ],
      "location": "Studio 2",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$135.00",
      "member_price": "$128.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/589",
      "image_url": null
    }
  },
  {
    "legacy_id": "605",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-2",
    "code": "26F-ADT-0028",
    "slug": "make-it-friday-candlemaking-nov-13-605",
    "title": "Make-It Friday: Candlemaking (Nov 13)",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 35,
    "member_price": 33,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-11-13 18:30:00",
    "ends_local": "2026-11-13 20:30:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/605",
    "instructor_display_text": "Felicia Crisden",
    "source_schedule_text": "Friday, November 13, 2026 | 6:30 PM – 8:30 PM",
    "source_location_text": "Studio 2",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "605",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "Felicia Crisden",
      "schedule": [
        "Friday, November 13, 2026",
        "6:30 PM – 8:30 PM"
      ],
      "location": "Studio 2",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$35.00",
      "member_price": "$33.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/605",
      "image_url": null
    }
  },
  {
    "legacy_id": "609",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "CER-HANDBUILDING",
    "code": "26F-ADT-0033",
    "slug": "make-it-friday-workshop-sgraffito-workshop-609",
    "title": "Make-It Friday Workshop: Sgraffito Workshop",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 35,
    "member_price": 33,
    "fee": 10,
    "fee_label": "Gas Kiln Fee",
    "starts_local": "2026-11-13 18:00:00",
    "ends_local": "2026-11-13 20:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/609",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Friday, November 13, 2026 | 6:00 PM – 8:00 PM",
    "source_location_text": "Ceramics Handbuilding",
    "source_category": "Ceramics",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "609",
      "category": "Ceramics",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Friday, November 13, 2026",
        "6:00 PM – 8:00 PM"
      ],
      "location": "Ceramics Handbuilding",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$35.00",
      "member_price": "$33.00 (members)",
      "fees": [
        "+ $10.00 (Gas Kiln Fee)"
      ],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/609",
      "image_url": null
    }
  },
  {
    "legacy_id": "610",
    "program_code": "ADULT-ART",
    "term_code": "2026-FALL",
    "facility_code": "STUDIO-2",
    "code": "26F-ADT-0034",
    "slug": "make-it-friday-workshop-printmaking-cards-610",
    "title": "Make-It Friday Workshop: Printmaking Cards",
    "level": "All Levels",
    "age_min": 18,
    "age_max": null,
    "price": 35,
    "member_price": 33,
    "fee": 0,
    "fee_label": null,
    "starts_local": "2026-11-13 18:30:00",
    "ends_local": "2026-11-13 20:00:00",
    "image_path": null,
    "image_alt": null,
    "external_registration_url": "https://canvas.allenslane.org/classes/610",
    "instructor_display_text": "TBD TBD",
    "source_schedule_text": "Friday, November 13, 2026 | 6:30 PM – 8:00 PM",
    "source_location_text": "Studio 2",
    "source_category": "All Media",
    "delivery_mode": "On-site",
    "source_registration_status": "open",
    "source_metadata": {
      "canvas_id": "610",
      "category": "All Media",
      "delivery": "On-site",
      "instructor": "TBD TBD",
      "schedule": [
        "Friday, November 13, 2026",
        "6:30 PM – 8:00 PM"
      ],
      "location": "Studio 2",
      "level_age": "All Levels, Ages 18 year+",
      "price": "$35.00",
      "member_price": "$33.00 (members)",
      "fees": [],
      "action": "Register",
      "is_full": false,
      "waitlist_only": false,
      "detail_url": "https://canvas.allenslane.org/classes/610",
      "image_url": null
    }
  }
]
$canvas_catalog$::jsonb) as row_data (
    legacy_id text,
    program_code text,
    term_code text,
    facility_code text,
    code text,
    slug text,
    title text,
    level text,
    age_min numeric,
    age_max numeric,
    price numeric,
    member_price numeric,
    fee numeric,
    fee_label text,
    starts_local text,
    ends_local text,
    image_path text,
    image_alt text,
    external_registration_url text,
    instructor_display_text text,
    source_schedule_text text,
    source_location_text text,
    source_category text,
    delivery_mode text,
    source_registration_status text,
    source_metadata jsonb
  )
)
insert into public.classes (
  program_id, term_id, facility_id, code, slug, title, level,
  age_min, age_max, capacity, minimum_enrollment, price, member_price, fee,
  starts_at, ends_at, timezone, image_path, image_alt, status, published_at,
  legacy_source, legacy_id, checkout_mode, external_registration_url,
  instructor_display_text, source_schedule_text, source_location_text,
  source_category, delivery_mode, fee_label, source_capacity_known,
  source_registration_status, source_metadata, source_synced_at
)
select
  (select p.id from public.programs p where p.code = source_rows.program_code),
  (select t.id from public.terms t where t.code = source_rows.term_code),
  (select f.id from public.facilities f where f.code = source_rows.facility_code),
  source_rows.code,
  source_rows.slug,
  source_rows.title,
  source_rows.level,
  source_rows.age_min,
  source_rows.age_max,
  0,
  0,
  source_rows.price,
  source_rows.member_price,
  source_rows.fee,
  timezone('America/New_York', source_rows.starts_local::timestamp),
  timezone('America/New_York', source_rows.ends_local::timestamp),
  'America/New_York',
  source_rows.image_path,
  source_rows.image_alt,
  'published',
  now(),
  'art_center_canvas',
  source_rows.legacy_id,
  'external',
  source_rows.external_registration_url,
  source_rows.instructor_display_text,
  source_rows.source_schedule_text,
  source_rows.source_location_text,
  source_rows.source_category,
  source_rows.delivery_mode,
  source_rows.fee_label,
  false,
  source_rows.source_registration_status,
  source_rows.source_metadata,
  '2026-08-06 20:45:00+00'::timestamptz
from source_rows
on conflict (legacy_source, legacy_id)
where legacy_source is not null and legacy_id is not null
do update set
  program_id = excluded.program_id,
  term_id = excluded.term_id,
  facility_id = excluded.facility_id,
  code = excluded.code,
  slug = excluded.slug,
  title = excluded.title,
  level = excluded.level,
  age_min = excluded.age_min,
  age_max = excluded.age_max,
  capacity = excluded.capacity,
  minimum_enrollment = excluded.minimum_enrollment,
  price = excluded.price,
  member_price = excluded.member_price,
  fee = excluded.fee,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  timezone = excluded.timezone,
  image_path = excluded.image_path,
  image_alt = excluded.image_alt,
  status = excluded.status,
  published_at = coalesce(public.classes.published_at, excluded.published_at),
  checkout_mode = excluded.checkout_mode,
  external_registration_url = excluded.external_registration_url,
  instructor_display_text = excluded.instructor_display_text,
  source_schedule_text = excluded.source_schedule_text,
  source_location_text = excluded.source_location_text,
  source_category = excluded.source_category,
  delivery_mode = excluded.delivery_mode,
  fee_label = excluded.fee_label,
  source_capacity_known = excluded.source_capacity_known,
  source_registration_status = excluded.source_registration_status,
  source_metadata = excluded.source_metadata,
  source_synced_at = excluded.source_synced_at,
  updated_at = now();

notify pgrst, 'reload schema';

commit;
